// This file must perfectly match docs/security/PDP_REASON_CODE_CATALOG.md
// Any drift here will fail CI checks.

export enum PdpReasonCode {
  // Supplier Governance
  SUPPLIER_MASTER_EXPIRED = 'SUPPLIER_MASTER_EXPIRED',
  SUPPLIER_NOT_APPROVED = 'SUPPLIER_NOT_APPROVED',
  SUPPLIER_FROZEN_MANUAL = 'SUPPLIER_FROZEN_MANUAL',

  // Contractor Governance
  CONTRACTOR_FROZEN_SUPPLIER_LAPSE = 'CONTRACTOR_FROZEN_SUPPLIER_LAPSE',
  CONTRACTOR_OFFBOARDED = 'CONTRACTOR_OFFBOARDED',
  CERTIFICATION_LAPSED_HIGH = 'CERTIFICATION_LAPSED_HIGH',
  CERTIFICATION_LAPSED_LOW = 'CERTIFICATION_LAPSED_LOW',
  MISSING_REQUIRED_DOCS = 'MISSING_REQUIRED_DOCS',

  // Purchase Order Governance
  PO_MISSING = 'PO_MISSING',
  PO_EXPIRED = 'PO_EXPIRED',
  PO_FUNDS_EXHAUSTED = 'PO_FUNDS_EXHAUSTED',
  PO_SUPPLIER_MISMATCH = 'PO_SUPPLIER_MISMATCH',

  // Financial Control Governance
  TIMESHEET_LATE_SUBMISSION = 'TIMESHEET_LATE_SUBMISSION',
  POST_EXPIRY_LABOR_PROHIBITED = 'POST_EXPIRY_LABOR_PROHIBITED',
  RETROACTIVE_LIMIT_EXCEEDED = 'RETROACTIVE_LIMIT_EXCEEDED',
  INVOICE_PO_MISMATCH = 'INVOICE_PO_MISMATCH',
}
