export const PROMOTION_ERROR = {
  STAGING_NOT_FOUND: 'STAGING_NOT_FOUND',
  NOT_PASSED: 'NOT_PASSED',
  ALREADY_PROMOTED: 'ALREADY_PROMOTED',
  INVALID_PIPELINE: 'INVALID_PIPELINE',
  MISSING_RESPONSIBLE_MANAGER: 'MISSING_RESPONSIBLE_MANAGER',
  RESPONSIBLE_MANAGER_NOT_VALID: 'RESPONSIBLE_MANAGER_NOT_VALID',
  MISSING_SOURCE_PERSON_ID: 'MISSING_SOURCE_PERSON_ID',
  DUPLICATE_IDENTITY: 'DUPLICATE_IDENTITY',
  SUPPLIER_UNRESOLVED: 'SUPPLIER_UNRESOLVED',
  SUPPLIER_OPERATIONAL_TRUST_NOT_GRANTED: 'SUPPLIER_OPERATIONAL_TRUST_NOT_GRANTED',
  NO_ACTIVE_CONTRACT: 'NO_ACTIVE_CONTRACT',
  MISSING_NORMALIZED_PAYLOAD: 'MISSING_NORMALIZED_PAYLOAD',
} as const;

export type PromotionErrorCode =
  (typeof PROMOTION_ERROR)[keyof typeof PROMOTION_ERROR];
