export const TTA_ERROR_CODES = {
  INVALID_STATUS: 'TTA_INVALID_STATUS',
  OVERLAP_CONFLICT: 'TTA_OVERLAP_CONFLICT',
  GAP_DETECTED: 'TTA_GAP_DETECTED',
  BRACKET_OVERLAP: 'TTA_BRACKET_OVERLAP',
  REQUIRED_FIELD_MISSING: 'TTA_REQUIRED_FIELD_MISSING',
  BASE_TAX_MISMATCH: 'TTA_BASE_TAX_MISMATCH',
  PUBLISH_APPROVAL_REQUIRED: 'TTA_PUBLISH_APPROVAL_REQUIRED',
  SELF_APPROVAL_BLOCKED: 'TTA_SELF_APPROVAL_BLOCKED',
  ALREADY_PUBLISHED: 'TTA_ALREADY_PUBLISHED',
  RUNTIME_SUPERSESSION_FAILED: 'TTA_RUNTIME_SUPERSESSION_FAILED',
  ROUTING_VERIFICATION_FAILED: 'TTA_ROUTING_VERIFICATION_FAILED',
  NOT_FOUND: 'TTA_NOT_FOUND',
  VALIDATION_FAILED: 'TTA_VALIDATION_FAILED',
  NO_BRACKETS: 'TTA_NO_BRACKETS',
  INVALID_RATE: 'TTA_INVALID_RATE',
  NEGATIVE_BASE_TAX: 'TTA_NEGATIVE_BASE_TAX',
  MULTIPLE_OPEN_ENDED: 'TTA_MULTIPLE_OPEN_ENDED',
  OPEN_ENDED_NOT_LAST: 'TTA_OPEN_ENDED_NOT_LAST',
  BRACKET_GAP_AT_ZERO: 'TTA_BRACKET_GAP_AT_ZERO',
  NULL_TO_NOT_OPEN_ENDED: 'TTA_NULL_TO_NOT_OPEN_ENDED',
  UNAUTHORIZED: 'TTA_UNAUTHORIZED',
  FORBIDDEN: 'TTA_FORBIDDEN',

  // Impact Analysis
  IMPACT_COUNTRY_MISMATCH: 'TTA_IMPACT_COUNTRY_MISMATCH',
  IMPACT_NO_CLOSED_PAYRUN: 'TTA_IMPACT_NO_CLOSED_PAYRUN',
  IMPACT_INVALID_STATUS: 'TTA_IMPACT_INVALID_STATUS',
  IMPACT_UNSUPPORTED_COUNTRY: 'TTA_IMPACT_UNSUPPORTED_COUNTRY',
  IMPACT_MISSING_PAYRUN: 'TTA_IMPACT_MISSING_PAYRUN',
  IMPACT_MISSING_PAYGROUP: 'TTA_IMPACT_MISSING_PAYGROUP',
  IMPACT_PAYRUN_NOT_FOUND: 'TTA_IMPACT_PAYRUN_NOT_FOUND',
  IMPACT_COMPUTE_FAILED: 'TTA_IMPACT_COMPUTE_FAILED',

  // Impact Analysis Export + Sign-off
  IMPACT_RUN_NOT_FOUND: 'TTA_IMPACT_RUN_NOT_FOUND',
  IMPACT_EXPORT_UNSUPPORTED: 'TTA_IMPACT_EXPORT_UNSUPPORTED',
  IMPACT_REVIEW_INVALID_STATUS: 'TTA_IMPACT_REVIEW_INVALID_STATUS',
  IMPACT_REVIEW_FOR_STALE_RUN: 'TTA_IMPACT_REVIEW_FOR_STALE_RUN',
  IMPACT_PUBLISH_REQUIRES_RUN: 'TTA_IMPACT_PUBLISH_REQUIRES_RUN',
  IMPACT_PUBLISH_REQUIRES_ACCEPTED_REVIEW: 'TTA_IMPACT_PUBLISH_REQUIRES_ACCEPTED_REVIEW',
  IMPACT_PUBLISH_RUN_STALE: 'TTA_IMPACT_PUBLISH_RUN_STALE',
} as const;

export type TtaErrorCode = (typeof TTA_ERROR_CODES)[keyof typeof TTA_ERROR_CODES];

export class TtaException extends Error {
  constructor(
    public readonly code: TtaErrorCode,
    message: string,
    public readonly details?: Record<string, unknown>,
    public readonly httpStatus: number = 400,
  ) {
    super(message);
    this.name = 'TtaException';
  }
}
