#!/usr/bin/env ts-node

/**
 * RBAC Permission Catalog Generator
 *
 * Reads the canonical backend permission catalog and generates:
 * 1. A JSON export at `backend/src/core/auth/permissions.catalog.json`
 * 2. A TypeScript constants file for the frontend at `frontend/lib/permissions.generated.ts`
 *
 * Usage:
 *   cd backend && npx ts-node scripts/generate-permissions.ts
 *
 * CI enforcement:
 *   npm run rbac:verify  (generates + git diff --exit-code)
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  PERMISSIONS,
  PERMISSION_GROUPS,
  ALL_PERMISSIONS,
  WILDCARD_ALL,
  WILDCARD_ACTION,
} from '../src/core/auth/permissions.constants';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const BACKEND_ROOT = path.resolve(__dirname, '..');
const PROJECT_ROOT = path.resolve(BACKEND_ROOT, '..');

const JSON_OUTPUT = path.join(
  BACKEND_ROOT,
  'src',
  'core',
  'auth',
  'permissions.catalog.json',
);

const FRONTEND_OUTPUT = path.join(
  PROJECT_ROOT,
  'frontend',
  'lib',
  'permissions.generated.ts',
);

// ---------------------------------------------------------------------------
// Generate JSON catalog
// ---------------------------------------------------------------------------

const catalog = {
  _generatorNote:
    'DO NOT EDIT — generated by backend/scripts/generate-permissions.ts',
  wildcards: {
    WILDCARD_ALL,
    WILDCARD_ACTION,
  },
  permissions: PERMISSIONS,
  allPermissions: Array.from(ALL_PERMISSIONS).sort(),
  groups: PERMISSION_GROUPS,
};

fs.writeFileSync(JSON_OUTPUT, JSON.stringify(catalog, null, 2) + '\n');
console.log(`✅ Written: ${path.relative(PROJECT_ROOT, JSON_OUTPUT)}`);

// ---------------------------------------------------------------------------
// Generate frontend TypeScript
// ---------------------------------------------------------------------------

const frontendTs = `/**
 * RBAC Permission Constants — GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: backend/scripts/generate-permissions.ts
 *
 * To regenerate:
 *   cd backend && npx ts-node scripts/generate-permissions.ts
 *
 * CI enforces that this file stays in sync with the backend catalog.
 */

// ---------------------------------------------------------------------------
// Permission catalog — mirrors backend/src/core/auth/permissions.constants.ts
// ---------------------------------------------------------------------------

export const PERMISSIONS = ${JSON.stringify(PERMISSIONS, null, 2)} as const;

// ---------------------------------------------------------------------------
// Flat set of all permissions (for validation)
// ---------------------------------------------------------------------------

export const ALL_PERMISSIONS: ReadonlySet<string> = new Set(${JSON.stringify(Array.from(ALL_PERMISSIONS).sort(), null, 2)});

// ---------------------------------------------------------------------------
// Permission groups (for UI display — role editors, permission pickers)
// ---------------------------------------------------------------------------

export const PERMISSION_GROUPS = ${JSON.stringify(PERMISSION_GROUPS, null, 2)};

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

/** Union type of all valid permission strings */
export type Permission = typeof ALL_PERMISSIONS extends ReadonlySet<infer T> ? T : never;

/** Resource names (top-level keys of PERMISSIONS) */
export type PermissionResource = keyof typeof PERMISSIONS;
`;

// Ensure frontend/lib directory exists
const frontendDir = path.dirname(FRONTEND_OUTPUT);
if (!fs.existsSync(frontendDir)) {
  fs.mkdirSync(frontendDir, { recursive: true });
}

fs.writeFileSync(FRONTEND_OUTPUT, frontendTs);
console.log(`✅ Written: ${path.relative(PROJECT_ROOT, FRONTEND_OUTPUT)}`);

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

console.log(`\n📋 Catalog summary:`);
console.log(`   Resources: ${Object.keys(PERMISSIONS).length}`);
console.log(`   Permissions: ${ALL_PERMISSIONS.size}`);
console.log(`   Groups: ${PERMISSION_GROUPS.length}`);
console.log(`\n🔒 Run 'npm run rbac:verify' in CI to enforce sync.`);
