-- Rename table from PascalCase to snake_case
ALTER TABLE "ResponsibleManagerAccountabilityTask" RENAME TO "responsible_manager_accountability_tasks";

-- Rename indexes
ALTER INDEX IF EXISTS "ResponsibleManagerAccountabilityTask_responsibleManagerEmployeeId_status_idx"
  RENAME TO "responsible_manager_accountability_tasks_responsibleManagerEmployeeId_status_idx";
ALTER INDEX IF EXISTS "ResponsibleManagerAccountabilityTask_engagementId_taskType_idx"
  RENAME TO "responsible_manager_accountability_tasks_engagementId_taskType_idx";
ALTER INDEX IF EXISTS "ResponsibleManagerAccountabilityTask_organizationId_idx"
  RENAME TO "responsible_manager_accountability_tasks_organizationId_idx";

-- Rename constraints
ALTER TABLE "responsible_manager_accountability_tasks"
  RENAME CONSTRAINT "ResponsibleManagerAccountabilityTask_pkey" TO "responsible_manager_accountability_tasks_pkey";
ALTER TABLE "responsible_manager_accountability_tasks"
  RENAME CONSTRAINT "ResponsibleManagerAccountabilityTask_organizationId_fkey" TO "responsible_manager_accountability_tasks_organizationId_fkey";
ALTER TABLE "responsible_manager_accountability_tasks"
  RENAME CONSTRAINT "ResponsibleManagerAccountabilityTask_engagementId_fkey" TO "responsible_manager_accountability_tasks_engagementId_fkey";
