/**
 * RBAC Permission Constants — GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: backend/scripts/generate-permissions.ts
 *
 * To regenerate:
 *   cd backend && npx ts-node scripts/generate-permissions.ts
 *
 * CI enforces that this file stays in sync with the backend catalog.
 */

// ---------------------------------------------------------------------------
// Permission catalog — mirrors backend/src/core/auth/permissions.constants.ts
// ---------------------------------------------------------------------------

export const PERMISSIONS = {
  "SUPPLIERS": {
    "CREATE": "suppliers:create",
    "READ": "suppliers:read",
    "UPDATE": "suppliers:update",
    "DELETE": "suppliers:delete"
  },
  "CONTRACTORS": {
    "CREATE": "contractors:create",
    "READ": "contractors:read",
    "UPDATE": "contractors:update",
    "DELETE": "contractors:delete"
  },
  "CONTRACTS": {
    "CREATE": "contracts:create",
    "READ": "contracts:read",
    "UPDATE": "contracts:update",
    "DELETE": "contracts:delete"
  },
  "ENGAGEMENTS": {
    "CREATE": "engagements:create",
    "READ": "engagements:read",
    "UPDATE": "engagements:update",
    "DELETE": "engagements:delete"
  },
  "TIMESHEETS": {
    "CREATE": "timesheets:create",
    "READ": "timesheets:read",
    "UPDATE": "timesheets:update",
    "DELETE": "timesheets:delete",
    "SUBMIT": "timesheets:submit",
    "APPROVE": "timesheets:approve"
  },
  "INVOICES": {
    "CREATE": "invoices:create",
    "READ": "invoices:read",
    "UPDATE": "invoices:update",
    "DELETE": "invoices:delete",
    "SUBMIT": "invoices:submit",
    "APPROVE": "invoices:approve"
  },
  "TAX_CLASSIFICATIONS": {
    "CREATE": "tax-classifications:create",
    "READ": "tax-classifications:read",
    "UPDATE": "tax-classifications:update",
    "DELETE": "tax-classifications:delete",
    "APPROVE": "tax-classifications:approve"
  },
  "WITHHOLDING": {
    "CREATE": "withholding:create",
    "READ": "withholding:read",
    "UPDATE": "withholding:update",
    "DELETE": "withholding:delete"
  },
  "PROJECTS": {
    "CREATE": "projects:create",
    "READ": "projects:read",
    "UPDATE": "projects:update",
    "DELETE": "projects:delete"
  },
  "ORGANIZATIONS": {
    "CREATE": "organizations:create",
    "READ": "organizations:read",
    "UPDATE": "organizations:update"
  },
  "ANALYTICS": {
    "READ": "analytics:read"
  },
  "PROFILE": {
    "READ": "profile:read",
    "UPDATE": "profile:update"
  },
  "USERS": {
    "CREATE": "users:create",
    "READ": "users:read",
    "UPDATE": "users:update",
    "DEACTIVATE": "users:deactivate"
  },
  "ROLES": {
    "CREATE": "roles:create",
    "READ": "roles:read",
    "UPDATE": "roles:update",
    "DELETE": "roles:delete",
    "ASSIGN": "roles:assign"
  },
  "AUDIT": {
    "READ": "audit:read"
  },
  "PDP_ACTIVATION": {
    "VIEW": "pdp-activation:view",
    "MANAGE": "pdp-activation:manage"
  },
  "PDP_EXCEPTIONS": {
    "VIEW": "pdp-exceptions:view",
    "REQUEST": "pdp-exceptions:request",
    "MANAGE": "pdp-exceptions:manage"
  },
  "PDP_TELEMETRY": {
    "VIEW": "pdp-telemetry:view"
  },
  "GOVERNANCE_ANALYTICS": {
    "VIEW": "governance-analytics:view",
    "EXPORT": "governance-analytics:export"
  },
  "GOVERNANCE_RISK": {
    "VIEW": "governance-risk:view",
    "MANAGE": "governance-risk:manage"
  },
  "EXTID_EVENTS": {
    "READ": "extid-events:read",
    "ACK": "extid-events:ack",
    "FAIL": "extid-events:fail"
  },
  "SUPPLIER_PROFILE": {
    "READ": "supplier-profile:read",
    "UPDATE": "supplier-profile:update"
  },
  "SUPPLIER_USERS": {
    "MANAGE": "supplier-users:manage"
  },
  "SUPPLIER_RESOURCES": {
    "READ": "supplier-resources:read",
    "CREATE": "supplier-resources:create"
  },
  "SUPPLIER_TIMESHEETS": {
    "READ": "supplier-timesheets:read",
    "SUBMIT": "supplier-timesheets:submit"
  },
  "SUPPLIER_INVOICES": {
    "SUBMIT": "supplier-invoices:submit"
  }
} as const;

// ---------------------------------------------------------------------------
// Flat set of all permissions (for validation)
// ---------------------------------------------------------------------------

export const ALL_PERMISSIONS: ReadonlySet<string> = new Set([
  "analytics:read",
  "audit:read",
  "contractors:create",
  "contractors:delete",
  "contractors:read",
  "contractors:update",
  "contracts:create",
  "contracts:delete",
  "contracts:read",
  "contracts:update",
  "engagements:create",
  "engagements:delete",
  "engagements:read",
  "engagements:update",
  "extid-events:ack",
  "extid-events:fail",
  "extid-events:read",
  "governance-analytics:export",
  "governance-analytics:view",
  "governance-risk:manage",
  "governance-risk:view",
  "invoices:approve",
  "invoices:create",
  "invoices:delete",
  "invoices:read",
  "invoices:submit",
  "invoices:update",
  "organizations:create",
  "organizations:read",
  "organizations:update",
  "pdp-activation:manage",
  "pdp-activation:view",
  "pdp-exceptions:manage",
  "pdp-exceptions:request",
  "pdp-exceptions:view",
  "pdp-telemetry:view",
  "profile:read",
  "profile:update",
  "projects:create",
  "projects:delete",
  "projects:read",
  "projects:update",
  "roles:assign",
  "roles:create",
  "roles:delete",
  "roles:read",
  "roles:update",
  "supplier-invoices:submit",
  "supplier-profile:read",
  "supplier-profile:update",
  "supplier-resources:create",
  "supplier-resources:read",
  "supplier-timesheets:read",
  "supplier-timesheets:submit",
  "supplier-users:manage",
  "suppliers:create",
  "suppliers:delete",
  "suppliers:read",
  "suppliers:update",
  "tax-classifications:approve",
  "tax-classifications:create",
  "tax-classifications:delete",
  "tax-classifications:read",
  "tax-classifications:update",
  "timesheets:approve",
  "timesheets:create",
  "timesheets:delete",
  "timesheets:read",
  "timesheets:submit",
  "timesheets:update",
  "users:create",
  "users:deactivate",
  "users:read",
  "users:update",
  "withholding:create",
  "withholding:delete",
  "withholding:read",
  "withholding:update"
]);

// ---------------------------------------------------------------------------
// Permission groups (for UI display — role editors, permission pickers)
// ---------------------------------------------------------------------------

export const PERMISSION_GROUPS = [
  {
    "resource": "SUPPLIERS",
    "label": "SUPPLIERS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "suppliers:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "suppliers:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "suppliers:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "suppliers:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "CONTRACTORS",
    "label": "CONTRACTORS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "contractors:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "contractors:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "contractors:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "contractors:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "CONTRACTS",
    "label": "CONTRACTS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "contracts:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "contracts:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "contracts:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "contracts:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "ENGAGEMENTS",
    "label": "ENGAGEMENTS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "engagements:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "engagements:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "engagements:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "engagements:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "TIMESHEETS",
    "label": "TIMESHEETS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "timesheets:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "timesheets:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "timesheets:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "timesheets:delete",
        "label": "Delete"
      },
      {
        "action": "SUBMIT",
        "value": "timesheets:submit",
        "label": "Submit"
      },
      {
        "action": "APPROVE",
        "value": "timesheets:approve",
        "label": "Approve"
      }
    ]
  },
  {
    "resource": "INVOICES",
    "label": "INVOICES",
    "permissions": [
      {
        "action": "CREATE",
        "value": "invoices:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "invoices:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "invoices:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "invoices:delete",
        "label": "Delete"
      },
      {
        "action": "SUBMIT",
        "value": "invoices:submit",
        "label": "Submit"
      },
      {
        "action": "APPROVE",
        "value": "invoices:approve",
        "label": "Approve"
      }
    ]
  },
  {
    "resource": "TAX_CLASSIFICATIONS",
    "label": "TAX CLASSIFICATIONS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "tax-classifications:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "tax-classifications:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "tax-classifications:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "tax-classifications:delete",
        "label": "Delete"
      },
      {
        "action": "APPROVE",
        "value": "tax-classifications:approve",
        "label": "Approve"
      }
    ]
  },
  {
    "resource": "WITHHOLDING",
    "label": "WITHHOLDING",
    "permissions": [
      {
        "action": "CREATE",
        "value": "withholding:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "withholding:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "withholding:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "withholding:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "PROJECTS",
    "label": "PROJECTS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "projects:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "projects:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "projects:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "projects:delete",
        "label": "Delete"
      }
    ]
  },
  {
    "resource": "ORGANIZATIONS",
    "label": "ORGANIZATIONS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "organizations:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "organizations:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "organizations:update",
        "label": "Update"
      }
    ]
  },
  {
    "resource": "ANALYTICS",
    "label": "ANALYTICS",
    "permissions": [
      {
        "action": "READ",
        "value": "analytics:read",
        "label": "Read"
      }
    ]
  },
  {
    "resource": "PROFILE",
    "label": "PROFILE",
    "permissions": [
      {
        "action": "READ",
        "value": "profile:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "profile:update",
        "label": "Update"
      }
    ]
  },
  {
    "resource": "USERS",
    "label": "USERS",
    "permissions": [
      {
        "action": "CREATE",
        "value": "users:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "users:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "users:update",
        "label": "Update"
      },
      {
        "action": "DEACTIVATE",
        "value": "users:deactivate",
        "label": "Deactivate"
      }
    ]
  },
  {
    "resource": "ROLES",
    "label": "ROLES",
    "permissions": [
      {
        "action": "CREATE",
        "value": "roles:create",
        "label": "Create"
      },
      {
        "action": "READ",
        "value": "roles:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "roles:update",
        "label": "Update"
      },
      {
        "action": "DELETE",
        "value": "roles:delete",
        "label": "Delete"
      },
      {
        "action": "ASSIGN",
        "value": "roles:assign",
        "label": "Assign"
      }
    ]
  },
  {
    "resource": "AUDIT",
    "label": "AUDIT",
    "permissions": [
      {
        "action": "READ",
        "value": "audit:read",
        "label": "Read"
      }
    ]
  },
  {
    "resource": "PDP_ACTIVATION",
    "label": "PDP ACTIVATION",
    "permissions": [
      {
        "action": "VIEW",
        "value": "pdp-activation:view",
        "label": "View"
      },
      {
        "action": "MANAGE",
        "value": "pdp-activation:manage",
        "label": "Manage"
      }
    ]
  },
  {
    "resource": "PDP_EXCEPTIONS",
    "label": "PDP EXCEPTIONS",
    "permissions": [
      {
        "action": "VIEW",
        "value": "pdp-exceptions:view",
        "label": "View"
      },
      {
        "action": "REQUEST",
        "value": "pdp-exceptions:request",
        "label": "Request"
      },
      {
        "action": "MANAGE",
        "value": "pdp-exceptions:manage",
        "label": "Manage"
      }
    ]
  },
  {
    "resource": "PDP_TELEMETRY",
    "label": "PDP TELEMETRY",
    "permissions": [
      {
        "action": "VIEW",
        "value": "pdp-telemetry:view",
        "label": "View"
      }
    ]
  },
  {
    "resource": "GOVERNANCE_ANALYTICS",
    "label": "GOVERNANCE ANALYTICS",
    "permissions": [
      {
        "action": "VIEW",
        "value": "governance-analytics:view",
        "label": "View"
      },
      {
        "action": "EXPORT",
        "value": "governance-analytics:export",
        "label": "Export"
      }
    ]
  },
  {
    "resource": "GOVERNANCE_RISK",
    "label": "GOVERNANCE RISK",
    "permissions": [
      {
        "action": "VIEW",
        "value": "governance-risk:view",
        "label": "View"
      },
      {
        "action": "MANAGE",
        "value": "governance-risk:manage",
        "label": "Manage"
      }
    ]
  },
  {
    "resource": "EXTID_EVENTS",
    "label": "EXTID EVENTS",
    "permissions": [
      {
        "action": "READ",
        "value": "extid-events:read",
        "label": "Read"
      },
      {
        "action": "ACK",
        "value": "extid-events:ack",
        "label": "Ack"
      },
      {
        "action": "FAIL",
        "value": "extid-events:fail",
        "label": "Fail"
      }
    ]
  },
  {
    "resource": "SUPPLIER_PROFILE",
    "label": "SUPPLIER PROFILE",
    "permissions": [
      {
        "action": "READ",
        "value": "supplier-profile:read",
        "label": "Read"
      },
      {
        "action": "UPDATE",
        "value": "supplier-profile:update",
        "label": "Update"
      }
    ]
  },
  {
    "resource": "SUPPLIER_USERS",
    "label": "SUPPLIER USERS",
    "permissions": [
      {
        "action": "MANAGE",
        "value": "supplier-users:manage",
        "label": "Manage"
      }
    ]
  },
  {
    "resource": "SUPPLIER_RESOURCES",
    "label": "SUPPLIER RESOURCES",
    "permissions": [
      {
        "action": "READ",
        "value": "supplier-resources:read",
        "label": "Read"
      },
      {
        "action": "CREATE",
        "value": "supplier-resources:create",
        "label": "Create"
      }
    ]
  },
  {
    "resource": "SUPPLIER_TIMESHEETS",
    "label": "SUPPLIER TIMESHEETS",
    "permissions": [
      {
        "action": "READ",
        "value": "supplier-timesheets:read",
        "label": "Read"
      },
      {
        "action": "SUBMIT",
        "value": "supplier-timesheets:submit",
        "label": "Submit"
      }
    ]
  },
  {
    "resource": "SUPPLIER_INVOICES",
    "label": "SUPPLIER INVOICES",
    "permissions": [
      {
        "action": "SUBMIT",
        "value": "supplier-invoices:submit",
        "label": "Submit"
      }
    ]
  }
];

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

/** Union type of all valid permission strings */
export type Permission = typeof ALL_PERMISSIONS extends ReadonlySet<infer T> ? T : never;

/** Resource names (top-level keys of PERMISSIONS) */
export type PermissionResource = keyof typeof PERMISSIONS;
